version: "3"
services:
  app:
    image: tiangolo/uvicorn-gunicorn:python3.8-alpine3.10
    ports:
      - 8081:80
    volumes:
      - $PWD/app:/app
      - $PWD/conf/repositories:/etc/apk/repositories
      - $PWD/conf/pip.conf:/root/.config/pip/pip.conf
