version: "3"
services:
  app:
    image: uvicorn-gunicorn:python3.8-alpine
    build:
      context: .
      dockerfile: ./docker_env/webserv/Dockerfile
    working_dir: /app
    ports:
      - 8080:80
    restart: always
    volumes:
      - $PWD/app:/app
      - $PWD/conf/repositories:/etc/apk/repositories
      - $PWD/conf/pip.conf:/root/.config/pip/pip.conf
